let items_array = [
  {
    name: "A Book",
    price: 0.69,
    img: "https://funci.org/wp-content/uploads/2009/02/Coran_cerrado-1024x576.jpg",
    alt: "The Quran",
    id: 1,
    count: 0,
  },
  {
    name: "[REDACTED]",
    price: 30.43,
    img: "https://external-preview.redd.it/lqDFDXXvfqMs7kyQ9y1FrGcQzdCE23uMPlcxFqo_oYE.png?width=640&crop=smart&auto=webp&s=1aad996b62437feb367356c6bed434385bda0699",
    alt: "A Chinese president that is photoshopped to look like Winnie the Pooh",
    id: 2,
    count: 0,
  },
  {
    name: "Charlie and the Giant P̶e̶a̶c̶h̶ Apple ",
    price: 1.01,
    img: "https://cdn.w600.comps.canstockphoto.com/red-apple-vector-clip-art_csp8020581.jpg",
    alt: "A stock image of an apple with a very visible watermark",
    id: 3,
    count: 0,
  },
  {
    name: "Rock Squid Ticket",
    price: 13.53,
    img: "https://i.kym-cdn.com/photos/images/original/001/592/949/76a.jpg",
    alt: "Dwayne the Rock Johnson photoshopped to look like Squidward",
    id: 4,
    count: 0,
  },
  {
    name: "What this",
    price: 40000.0,
    img: "https://i.etsystatic.com/10464795/r/il/743872/2285198101/il_fullxfull.2285198101_hgjr.jpg",
    alt: "Pot of Greed:(Draw two cards)",
    id: 5,
    count: 0,
  },
  {
    name: "2 Beatles",
    price: 178000.62,
    img: "https://i.ytimg.com/vi/QBpvlVJigjk/maxresdefault.jpg",
    alt: "Two volkswagon vehicles placed next to each other",
    id: 6,
    count: 0,
  },
  {
    name: "RTX 3090",
    price: 2.99,
    img: "https://www.crtsite.com/big/cathode%20ray%20technology/first%20crt-big.jpg",
    alt: "A cathode ray tube",
    id: 7,
    count: 0,
  },
  {
    name: "Free Real Estate",
    price: 325100.24,
    img: "https://imgix.bustle.com/inverse/be/0f/67/67/7275/4ac0/8568/b018c5560091/league-of-nation-3-copyjpg.jpeg?w=1200&h=630&fit=crop&crop=faces&fm=jpg",
    alt: "meme featuring It's Free Real Estate",
    id: 8,
    count: 0,
  },
  {
    name: "Funky looking gun",
    price: 1200000000.58,
    img: "https://i.pinimg.com/474x/cc/a4/7d/cca47deac8bc89205525166c0a2edbe8--guns-war.jpg",
    alt: "A gun that is manufactured(?) to point at the user",
    id: 9,
    count: 0,
  },
  {
    name: "LOOOOOOONG MAN",
    price: 3.99,
    img: "https://cdn.vox-cdn.com/thumbor/jPz28TvhYf13tmhsSS9U3VTwnME=/1400x1400/filters:format(png)/cdn.vox-cdn.com/uploads/chorus_asset/file/10594785/1.png",
    alt: "A japanese ad on chewing gum",
    id: 10,
    count: 0,
  },
  {
    name: "a̶̢͈̘̼̭̲͚̮̪͔̩̬̭̼̐̈́̅͝ ̷̹̺̬̭̼͖̠̜̗̬̠̱̣̎͆̾̒͐̽͒̚͜s̷̛̟̲͒̅́̆̿̃͝͝t̵͇̥̩̲̲̹́̈́͛͑̽͗͗̉̈́ä̶͍́̍̎̿̈́̇̕ẗ̷͖͚́̄̽͌̃͘͝ǘ̷̳̦͕̣̦͍͍̹̞͆̍̌̐̌̊̒̃͊̕ͅe̵̗͖̍̋̍͜͜",
    price: "F̵̛͙̞̰͆̂̏͗̆̐̿̆̉̕̕͠R̵̡̧̦͎̤̪̩̣̱͉̹͔̠͈͕̋R̸̖͍̲͙̲̓̃̅͛̎͋͑̓̈́̈́̏̔͘͜͠E̵̬̮͙̿͑̇̓̾͑͐̐̐͗̂͝͠͝Ę̴̛̗̩̭͎̣̻̣̤͇̟͕̑͌̄̊̅̀̀̅͌́̌̕̚͠Ę̵͕͈̥̘̗̞̼̲͌̂́͆̔̅̍̐̑̕͜ͅË̵̲̣͇̰̘̻͈̱͕̺́͋̾̓͌̚̕͝",
    img: "https://i.pinimg.com/originals/34/41/53/344153653a39729c21c8a7b431e2d29b.png",
    alt: "SCP-173; Will break your neck if you look away",
    id: 10,
    count: 0,
  },
  {
    name: "Rick",
    price: 113.99,
    img: "https://c.tenor.com/yheo1GGu3FwAAAAM/rick-roll-rick-ashley.gif",
    alt: "Never gonna give you up",
    id: 10,
    count: 0,
  },
];
export { items_array };
// const items_array = [
//   { name: "carrots", id: 1, count: 1, price: "$1.22" },
//   { name: "spinach", id: 2, count: 1, price: "$3" },
//   { name: "cookies", id: 3, count: 1, price: "$2" },
//   { name: "lettuce", id: 4, count: 1, price: "$1.71" },
//   { name: "avocado", id: 5, count: 1, price: "$1.5" },
// ];
// export { items_array };
