const sections = [
  {
    name: "Tsuburaya Productions",
    pic1: "/ultraman-america.webp",
    alt1: "Ultra brothers, Father of Ultra, and Mother of Ultra posing together",
    paragraph: "somethingsomething",
    id: 1,
  },
  {
    name: "What is Tsuburaya Productions?",
    pic1: "/Ultraman.webp",
    pic2: "/Eiji Tsuburaya.webp",
    alt1: "Ultraman Posing",
    alt2: "Eiji Tsuburaya",
    paragraph: "somethingsomething",
    id: 2,
  },
  {
    name: "Iconic Series made by them",
    pic1: "/Ultraman_Tiga.webp",
    alt1: "Ultraman Tiga staring backwards menacingly",
    paragraph: "somethingsomething",
    id: 3,
  },
  {
    name: "Works that are inspired by them",
    pic1: "/Hideaki Anno.jpg",
    pic2: "/Evangelion.jpg",
    alt1: "Hideaki Anno",
    alt2: "Evangelion picture",
    paragraph: "somethingsomething",
    id: 4,
  },
  {
    name: "Latest Works, Projects, and Series",
    pic1: "/Ultraman_Decker_poster.webp",
    pic2: "/Shin Ultraman Poster.jpg",
    pic3: "/UGFTDCPoster2.webp",
    alt1: "Ultraman Decker Poster",
    alt2: "Shin Ultraman Poster",
    alt3: "Ultra Galaxy Fight: The Destined Crossroad Poster",
    paragraph: "somethingsomething",
    id: 5,
  },
];
export { sections };
