const sections = [
  {
    name: "Front Page",
    pic1: "/ultraman-america.webp",
    alt1: "",
    paragraph: "somethingsomething",
    id: 1,
  },
  {
    name: "Eiji Tsuburaya",
    pic1: "/Ultraman.webp",
    pic2: "/Eiji Tsuburaya.webp",
    alt1: "",
    alt2: "",
    paragraph: "somethingsomething",
    id: 2,
  },
  {
    name: "Iconic Series",
    pic1: "/Ultraman_Tiga.webp",
    alt1: "",
    paragraph: "somethingsomething",
    id: 3,
  },
  {
    name: "Hideaki Anno",
    pic1: "/Hideaki Anno.jpg",
    pic2: "/Evangelion.jpg",
    alt1: "",
    alt2: "",
    paragraph: "somethingsomething",
    id: 4,
  },
  {
    name: "Latest Projects",
    pic1: "/Ultraman_Decker_poster.webp",
    pic2: "/Shin Ultraman Poster.jpg",
    pic3: "/UGFTDCPoster2.webp",
    alt1: "",
    alt2: "",
    alt3: "",
    paragraph: "somethingsomething",
    id: 5,
  },
];
export { sections };
